[package]
name = "neuropong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "neuropong"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
ggez = "0.9.3"
rand = "0.8.5"